steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/play-nestjs/api-server', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/play-nestjs/api-server']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'api-server',
        '--image',
        'gcr.io/play-nestjs/api-server',
        '--region',
        'asia-northeast1',
      ]
images:
  - gcr.io/play-nestjs/api-server
